# Tavily constants
[tavily]
days = 100
topic = "general"

# LLM Configuration
[llm]
model_name = "llama-3.3-70b-versatile"

# Parameters
[parameters]
query = "" 
save_final_state = true
task_length = 3
max_concurrency = 1
